[env:ReLow60]
board = genericAT32F405RCT7
board_build.ldscript = linker/at32f405xc.ld
build_flags = ${env.build_flags}
build_src_filter = ${env.build_src_filter}
build_src_flags = ${env.build_src_flags}
	-Werror
	-Wall
	-Wextra
	-Wsign-conversion
	-Wswitch-default
	-Wswitch
	-Wdouble-promotion
	-Wstrict-prototypes
	-Wno-unused-parameter
extra_scripts = pre:scripts/get_deps.py
	pre:scripts/validate.py
	pre:scripts/make.py
	pre:scripts/metadata.py
	post:scripts/iap_image.py
framework = at32firmlib
lib_deps = https://github.com/hathach/tinyusb.git#0.20.0
platform = https://github.com/ArteryTek/platform-arterytekat32.git
upload_protocol = dfu

